Decade.create(name: "1990's")
Decade.create(name: "2000's")
Decade.create(name: "2010's")

CategoryDecade.create(category_id: 1, decade_id: 1)
CategoryDecade.create(category_id: 2, decade_id: 1)
CategoryDecade.create(category_id: 3, decade_id: 1)
CategoryDecade.create(category_id: 4, decade_id: 1)
CategoryDecade.create(category_id: 5, decade_id: 1)

CategoryDecade.create(category_id: 6, decade_id: 2)
CategoryDecade.create(category_id: 7, decade_id: 2)
CategoryDecade.create(category_id: 8, decade_id: 2)
CategoryDecade.create(category_id: 9, decade_id: 2)
CategoryDecade.create(category_id: 10, decade_id: 2)

CategoryDecade.create(category_id: 11, decade_id: 3)
CategoryDecade.create(category_id: 12, decade_id: 3)
CategoryDecade.create(category_id: 13, decade_id: 3)
CategoryDecade.create(category_id: 14, decade_id: 3)
CategoryDecade.create(category_id: 15, decade_id: 3)

Category.create(name: "Cartoons")
Category.create(name: "Sports")
Category.create(name: "Video Games")
Category.create(name: "Music")
Category.create(name: "TV/MOVIES")


Category.create(name: "Cartoons")
Category.create(name: "Sports")
Category.create(name: "Video Games")
Category.create(name: "Music")
Category.create(name: "TV/MOVIES")

Category.create(name: "Cartoons")
Category.create(name: "Sports")
Category.create(name: "Video Games")
Category.create(name: "Music")
Category.create(name: "TV/MOVIES")

CategoryMemory.create(category_id: 1, memory_id: 4)
CategoryMemory.create(category_id: 1, memory_id: 5)
CategoryMemory.create(category_id: 1, memory_id: 6)
CategoryMemory.create(category_id: 3, memory_id: 1)
CategoryMemory.create(category_id: 3, memory_id: 2)
CategoryMemory.create(category_id: 3, memory_id: 3)
CategoryMemory.create(category_id: 2, memory_id: 7)
CategoryMemory.create(category_id: 2, memory_id: 8)
CategoryMemory.create(category_id: 2, memory_id: 9)
CategoryMemory.create(category_id: 4, memory_id: 10)
CategoryMemory.create(category_id: 4, memory_id: 11)
CategoryMemory.create(category_id: 4, memory_id: 12)
CategoryMemory.create(category_id: 5, memory_id: 13)
CategoryMemory.create(category_id: 5, memory_id: 14)
CategoryMemory.create(category_id: 5, memory_id: 15)
CategoryMemory.create(category_id: 2, memory_id: 16)


CategoryMemory.create(category_id: 6, memory_id: 17)
CategoryMemory.create(category_id: 7, memory_id: 18)
CategoryMemory.create(category_id: 8, memory_id: 19)
CategoryMemory.create(category_id: 9, memory_id: 20)
CategoryMemory.create(category_id: 10, memory_id: 21)

CategoryMemory.create(category_id: 11, memory_id: 22)
CategoryMemory.create(category_id: 12, memory_id: 23)
CategoryMemory.create(category_id: 13, memory_id: 24)
CategoryMemory.create(category_id: 14, memory_id: 25)
CategoryMemory.create(category_id: 15, memory_id: 26)
CategoryMemory.create(category_id: 15, memory_id: 27)
CategoryMemory.create(category_id: 4, memory_id: 28)
CategoryMemory.create(category_id: 1, memory_id: 29)
CategoryMemory.create(category_id: 5, memory_id: 30)
CategoryMemory.create(category_id: 1, memory_id: 31)
CategoryMemory.create(category_id: 1, memory_id: 32)
CategoryMemory.create(category_id: 1, memory_id: 33)
CategoryMemory.create(category_id: 1, memory_id: 34)
CategoryMemory.create(category_id: 1, memory_id: 35)
CategoryMemory.create(category_id: 1, memory_id: 36)
CategoryMemory.create(category_id: 1, memory_id: 37)
CategoryMemory.create(category_id: 1, memory_id: 38)
CategoryMemory.create(category_id: 1, memory_id: 39)
CategoryMemory.create(category_id: 1, memory_id: 40)
CategoryMemory.create(category_id: 1, memory_id: 41)
CategoryMemory.create(category_id: 1, memory_id: 42)
CategoryMemory.create(category_id: 2, memory_id: 43)
CategoryMemory.create(category_id: 2, memory_id: 44)
CategoryMemory.create(category_id: 2, memory_id: 45)
CategoryMemory.create(category_id: 2, memory_id: 46)
CategoryMemory.create(category_id: 2, memory_id: 47)
CategoryMemory.create(category_id: 2, memory_id: 48)
CategoryMemory.create(category_id: 2, memory_id: 49)
CategoryMemory.create(category_id: 2, memory_id: 50)
CategoryMemory.create(category_id: 3, memory_id: 51)
CategoryMemory.create(category_id: 3, memory_id: 52)
CategoryMemory.create(category_id: 3, memory_id: 53)
CategoryMemory.create(category_id: 3, memory_id: 54)
CategoryMemory.create(category_id: 3, memory_id: 55)
CategoryMemory.create(category_id: 3, memory_id: 56)
CategoryMemory.create(category_id: 3, memory_id: 57)
CategoryMemory.create(category_id: 3, memory_id: 58)
CategoryMemory.create(category_id: 3, memory_id: 59)
CategoryMemory.create(category_id: 3, memory_id: 60)
CategoryMemory.create(category_id: 4, memory_id: 61)
CategoryMemory.create(category_id: 4, memory_id: 62)
CategoryMemory.create(category_id: 4, memory_id: 63)
CategoryMemory.create(category_id: 4, memory_id: 64)
CategoryMemory.create(category_id: 4, memory_id: 65)
CategoryMemory.create(category_id: 4, memory_id: 66)
CategoryMemory.create(category_id: 4, memory_id: 67)
CategoryMemory.create(category_id: 4, memory_id: 68)
CategoryMemory.create(category_id: 4, memory_id: 69)
CategoryMemory.create(category_id: 4, memory_id: 70)
CategoryMemory.create(category_id: 5, memory_id: 71)
CategoryMemory.create(category_id: 5, memory_id: 72)
CategoryMemory.create(category_id: 5, memory_id: 73)
CategoryMemory.create(category_id: 1, memory_id: 74)
CategoryMemory.create(category_id: 5, memory_id: 75)
CategoryMemory.create(category_id: 5, memory_id: 76)
CategoryMemory.create(category_id: 5, memory_id: 77)
CategoryMemory.create(category_id: 5, memory_id: 78)
CategoryMemory.create(category_id: 5, memory_id: 79)
CategoryMemory.create(category_id: 5, memory_id: 80)
CategoryMemory.create(category_id: 5, memory_id: 81)
CategoryMemory.create(category_id: 5, memory_id: 82)
CategoryMemory.create(category_id: 5, memory_id: 83)
CategoryMemory.create(category_id: 5, memory_id: 84)
CategoryMemory.create(category_id: 5, memory_id: 85)

CategoryMemory.create(category_id: 6, memory_id: 86)
CategoryMemory.create(category_id: 6, memory_id: 87)
CategoryMemory.create(category_id: 6, memory_id: 88)
CategoryMemory.create(category_id: 6, memory_id: 89)
CategoryMemory.create(category_id: 6, memory_id: 90)
CategoryMemory.create(category_id: 6, memory_id: 91)
CategoryMemory.create(category_id: 6, memory_id: 92)
CategoryMemory.create(category_id: 6, memory_id: 93)
CategoryMemory.create(category_id: 6, memory_id: 94)
CategoryMemory.create(category_id: 6, memory_id: 95)

CategoryMemory.create(category_id: 7, memory_id: 96)
CategoryMemory.create(category_id: 7, memory_id: 97)
CategoryMemory.create(category_id: 7, memory_id: 98)
CategoryMemory.create(category_id: 7, memory_id: 99)
CategoryMemory.create(category_id: 7, memory_id: 100)
CategoryMemory.create(category_id: 7, memory_id: 101)
CategoryMemory.create(category_id: 7, memory_id: 102)
CategoryMemory.create(category_id: 7, memory_id: 103)
CategoryMemory.create(category_id: 7, memory_id: 104)
CategoryMemory.create(category_id: 7, memory_id: 105)

CategoryMemory.create(category_id: 8, memory_id: 106)
CategoryMemory.create(category_id: 8, memory_id: 107)
CategoryMemory.create(category_id: 8, memory_id: 108)
CategoryMemory.create(category_id: 8, memory_id: 109)
CategoryMemory.create(category_id: 8, memory_id: 110)
CategoryMemory.create(category_id: 8, memory_id: 111)
CategoryMemory.create(category_id: 8, memory_id: 112)
CategoryMemory.create(category_id: 8, memory_id: 113)
CategoryMemory.create(category_id: 8, memory_id: 114)
CategoryMemory.create(category_id: 8, memory_id: 115)


CategoryMemory.create(category_id: 9, memory_id: 116)
CategoryMemory.create(category_id: 9, memory_id: 117)
CategoryMemory.create(category_id: 9, memory_id: 118)
CategoryMemory.create(category_id: 9, memory_id: 119)
CategoryMemory.create(category_id: 9, memory_id: 120)
CategoryMemory.create(category_id: 9, memory_id: 121)
CategoryMemory.create(category_id: 9, memory_id: 122)
CategoryMemory.create(category_id: 9, memory_id: 123)
CategoryMemory.create(category_id: 9, memory_id: 124)
CategoryMemory.create(category_id: 9, memory_id: 125)

CategoryMemory.create(category_id: 10, memory_id: 126)
CategoryMemory.create(category_id: 10, memory_id: 127)
CategoryMemory.create(category_id: 10, memory_id: 128)
CategoryMemory.create(category_id: 10, memory_id: 129)
CategoryMemory.create(category_id: 10, memory_id: 130)
CategoryMemory.create(category_id: 10, memory_id: 131)
CategoryMemory.create(category_id: 10, memory_id: 132)
CategoryMemory.create(category_id: 10, memory_id: 133)
CategoryMemory.create(category_id: 10, memory_id: 134)
CategoryMemory.create(category_id: 10, memory_id: 135)













Memory.create(name: "Mega Man", picture: "http://i.stack.imgur.com/B7Soz.gif", video: "https://www.youtube.com/embed/ffPmcvwn0qE?autoplay=1", text: "Megaman is the greatest of all time.")
Memory.create(name: "Mario", picture: "http://vignette4.wikia.nocookie.net/fantendo/images/f/f5/Super_mario_by_mintenndo-d62lh70.png/revision/latest?cb=20130804000236", video: "https://www.youtube.com/embed/1FnPe6tinVs?autoplay=1", text: "Mario is the greatest of all time.")
Memory.create(name: "Golden Eye", picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-01/enhanced/webdr03/11/14/enhanced-buzz-17504-1389467654-3.jpg", video: "https://www.youtube.com/embed/a4qJ8wNfgXY?autoplay=1", text: "JAMES BOND is the greatest of all time.")
Memory.create(name: "Batman", picture: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0b/Batman_the_Animated_Series_logo.jpg/250px-Batman_the_Animated_Series_logo.jpg", video: "https://www.youtube.com/embed/-XJ3HJXxDwc?autoplay=1", text: "HELLO I'm BATMAN")
Memory.create(name: "X-Men", picture: "https://www.scifinow.co.uk/wp-content/uploads/2016/02/X-Men-The-Animated-Series.jpg", video: "https://www.youtube.com/embed/7IzSGvXc_PM?autoplay=1", text: "HELLO I'm an X-Men")
Memory.create(name: "Spiderman", picture: "http://images5.fanpop.com/image/photos/29700000/Spiderman-1994-spiderman-the-animated-series-1994-29730956-333-250.jpg", video: "https://www.youtube.com/embed/DZGN9fZvQhc?autoplay=1", text: "Hello I'm Spiderman")
Memory.create(name: "Chicago Bulls", picture: "http://d1d6pt83jmgnu9.cloudfront.net/enlarged_image/2796.jpg", video: "https://www.youtube.com/embed/o03gO5Xdmtg?autoplay=1", text: "THE CHICAGO BULLS")
Memory.create(name: "New York Yankees", picture: "https://www.sportsposterwarehouse.com/catImages/yanks1.jpg", video: "https://www.youtube.com/embed/sJe2dNJ3q48?autoplay=1", text: "The New York Yankees are the champs")
Memory.create(name: "San Francisco 49ers", picture: "http://static.nfl.com/static/content/public/pg-photo/2014/10/21/0ap3000000415145/san-francisco-49ers-18-consecutive-road-wins-from-1988-1990_pg_600.jpg", video: "https://www.youtube.com/embed/KQz-bWtfto0?autoplay=1", text: "The San Francisco 49ers are the champs")
Memory.create(name: "Creep", picture: "https://i.ytimg.com/vi/EYt_qVCFmAg/maxresdefault.jpg", video: "https://www.youtube.com/embed/XFkzRNyygfk?autoplay=1", text: "Radiohead")
Memory.create(name: "Baby One More Time", picture: "http://65.media.tumblr.com/7855d1f8d841703729cfa393c0171089/tumblr_inline_mtbwljIkSs1qmk5sn.jpg", video: "https://www.youtube.com/embed/C-u5WLJ9Yk4?autoplay=1", text: "Britney Spears")
Memory.create(name: "Enter Sandman", picture: "http://gravisludus.com/wp-content/uploads/2015/08/metallica___enter_sandman_v2_0_by_zerolevels-d3jal7z.png", video: "https://www.youtube.com/embed/uY3LAFJbKyY?autoplay=1", text: "Enter Sandman")
Memory.create(name: "Pulp Fiction", picture: "http://images.mentalfloss.com/sites/default/files/pulpfiction.jpeg", video: "https://www.youtube.com/embed/Mnb_3ibUp38?autoplay=1", text: "Pulp Fiction")
Memory.create(name: "The Lion King", picture: "http://img.wallpaperfolder.com/f/460532E9BA43/cartoons-lion-king-timon-simba.jpg", video: "https://www.youtube.com/embed/HwSKkKrUzUk?autoplay=1", text: "The Lion King")
Memory.create(name: "The Matrix", picture: "http://images.amcnetworks.com/ifc.com/wp-content/uploads/2015/01/The-Matrix.jpg", video: "https://www.youtube.com/embed/KNrSNcaYiZg?autoplay=1", text: "The Matrix")
Memory.create(name: "Stone Cold Steve Austin", picture: "http://www.wwe.com/f/styles/wwe_large/public/rd-talent/Bio/Steve_Austin_bio.jpg", video: "https://www.youtube.com/embed/MOzjBO2dsmY?autoplay=1", text: "STONE COLD STEVE AUSTIN")
Memory.create(name: "YU GI OH", picture: "https://i.ytimg.com/vi/2AKGWH-hcCk/maxresdefault.jpg", video: "https://www.youtube.com/embed/IVmtUK_1jh4?autoplay=1", text: "YU GI OH")
Memory.create(name: "Sacramento Kings", picture: "http://cdn2.vox-cdn.com/assets/4709198/1037fc2e3696fe50c74abb21fd982e4d.jpg", video: "https://www.youtube.com/embed/e9vvy9m84-U?autoplay=1", text: "Sacramento Kings")
Memory.create(name: "Kingdom Hearts II", picture: "http://vignette3.wikia.nocookie.net/kingdomhearts/images/b/b3/KH2-cover.png/revision/latest?cb=20121218160127", video: "https://www.youtube.com/embed/cbEvmJmw7fI?autoplay=1", text: "Kingdom Hearts II")
Memory.create(name: "MGMT KIDS", picture: "http://img.wennermedia.com/660-width/rs-136114-e894fb4c61b4707398dbb0518efd1511cc181ab1.jpg", video: "https://www.youtube.com/embed/wFZYa1iOnCE?autoplay=1", text: "MGMT KIDS")
Memory.create(name: "DARK KNIGHT", picture: "http://www.geek.com/wp-content/uploads/2016/02/batmans.jpg", video: "https://www.youtube.com/embed/_PZpmTj1Q8Q?autoplay=1", text: "DARK KNIGHT")
Memory.create(name: "Adventure", picture: "http://www.infiniteguest.org/wp-content/uploads/2015/06/adventure-time.jpg", video: "https://www.youtube.com/embed/BHjg6cTxmrQ?autoplay=1", text: "Adventure Time")
Memory.create(name: "SF GIANTS", picture: "http://sports-rings.com/newsletter_images/flan1.jpg", video: "https://www.youtube.com/embed/uogT8X26-ko?autoplay=1", text: "San Francisco Giants")
Memory.create(name: "Final Fantasy XV", picture: "http://static1.gamespot.com/uploads/screen_kubrick/1365/13658182/2917045-finalfantasy15_e32015_20150610_v1thumb.jpg", video: "https://www.youtube.com/embed/otVk3EEjgd8?autoplay=1", text: "Final Fantasy XV")
Memory.create(name: "Porter Robinson Divinity", picture: "https://i.ytimg.com/vi/si81bIoZRJQ/maxresdefault.jpg", video: "https://www.youtube.com/embed/si81bIoZRJQ?autoplay=1", text: "Porter Robinson Divinity")

Memory.create(name: "Game of Thrones", picture: "https://i.kinja-img.com/gawker-media/image/upload/c9lzmv4d3mgzpnyntz7s.jpg", video: "https://www.youtube.com/embed/s7L2PVdrb_8?autoplay=1", text: "Game of Thrones")

Memory.create(name: "Star Wars Episode VII", picture: "https://mostlyfilm.files.wordpress.com/2015/12/star-wars-7-the-force-awakens-could-kylo-ren-really-be-a-skywalker-668067.jpg", video: "https://www.youtube.com/embed/sGbxmsDFVnE?autoplay=1", text: "Star Wars Episode VII")
Memory.create(name: "Everlong", picture: "http://www.musiclipse.com/wp-content/uploads/2014/03/Foo-Fighters-Logo.jpg", video: "https://www.youtube.com/embed/8pHELrsqGgU?autoplay=1", text: "Everlong")
Memory.create(name: "Pokemon", picture: "http://vignette2.wikia.nocookie.net/pokemon/images/e/ef/025Pikachu_Pokemon_Mystery_Dungeon_Red_and_Blue_Rescue_Teams.png/revision/latest?cb=20150105233050", video: "https://www.youtube.com/embed/NcfdoSuC6MI?autoplay=1", text: "Pokemon!")
Memory.create(name: "Mighty Morphing Power Rangers", picture: "http://assets1.ignimgs.com/2016/05/06/mighty-morphin-s1-power-rangersjpg-652e5e_765w.jpg", video: "https://www.youtube.com/embed/HWzYln3md4I?autoplay=1", text: "Power Rangers")
Memory.create(name: "Tiny Toon Adventures", picture: "http://2.media.dorkly.cvcdn.com/32/96/875653c65af61dd095db599209c0fb38.jpg", video: "https://www.youtube.com/embed/3EiEX4tmCfY?autoplay=1", text: "Tiny Toon Adventures" )
Memory.create(name: "Doug", picture: "http://www.strangekidsclub.com/wp-content/uploads/2015/06/Doug-Funni-nickelodeon.jpg", video: "https://www.youtube.com/embed/Hygi3PlZI0Y?autoplay=1", text: "Doug" )
Memory.create(name: "Rugrats", picture: "http://cdn1.pri.org/sites/default/files/Rugrats_backdrop.jpg", video: "https://www.youtube.com/embed/xfzynwmrlok?autoplay=1", text: "Rugrats" )
Memory.create(name: "Pinky and the Brain", picture: "https://upload.wikimedia.org/wikipedia/en/4/47/Pinky_and_the_Brain_vol1.jpg", video: "https://www.youtube.com/embed/GBkT19uH2RQ?autoplay=1", text: "Pinky and the Brain" )
Memory.create(name: "Dexter's Laboratory", picture: "https://lh5.googleusercontent.com/--7HbGXIIB5o/UwrB6MPmwKI/AAAAAAAAAEs/T67EMke9lvg/w1497-h1501/DEXTER-FROM-DEXTERS-LABORATORY.png", video: "https://www.youtube.com/embed/tl5qccIJqMk?autoplay=1", text: "Dexter's Laboratory" )
Memory.create(name: "Hey Arnold", picture: "http://i2.wp.com/pmcvariety.files.wordpress.com/2015/11/1_hey-arnold.jpg?crop=24px%2C346px%2C2695px%2C1500px&resize=670%2C377&ssl=1", video: "https://www.youtube.com/embed/vUsnJ9jlwns?autoplay=1", text: "Hey Arnold" )
Memory.create(name: "Arthur", picture: "http://vignette2.wikia.nocookie.net/arthur/images/3/38/Arthur_Portal.jpg/revision/latest?cb=20121126055220", video: "https://www.youtube.com/embed/7zkX6kfnWbk?autoplay=1", text: "Arthur" )
Memory.create(name: "Johnny Bravo", picture: "http://dessins-animes.com/da/johnny_bravo/images/johnnybravo4.jpg", video: "https://www.youtube.com/embed/KdRhQ669s2c?autoplay=1", text: "Johnny Bravo" )
Memory.create(name: "Powerpuff Girls", picture: "https://cdn0.vox-cdn.com/thumbor/D5tkf71EzgSCWn4GeYKgt2NtHTw=/110x0:1887x1000/1280x720/cdn0.vox-cdn.com/uploads/chorus_image/image/49306135/o-POWERPUFF-GIRLS-facebook.0.0.jpg", video: "https://www.youtube.com/embed/4mmCMUPCNgE?autoplay=1", text: "Powerpuff Girls" )
Memory.create(name: "Spongebob Squarepants", picture: "https://thenypost.files.wordpress.com/2015/08/spongebob-e1441057213584.jpg?quality=90&strip=all&w=664&h=441&crop=1", video: "https://www.youtube.com/embed/r9L4AseD-aA?autoplay=1", text: "Spongebob Squarepants" )
Memory.create(name: "Batman Beyond", picture: "http://i.kinja-img.com/gawker-media/image/upload/adnmybsmrdrfnftahgc8.jpg", video: "https://www.youtube.com/embed/DVdTbiLku48?autoplay=1", text: "Batman Beyond" )
Memory.create(name: "Futurama", picture: "https://msu.edu/~tdc/Futurama/FuturamaComposition1024.jpg", video: "https://www.youtube.com/embed/xA_goQ_qEMA?autoplay=1", text: "Futurama" )
Memory.create(name: "Jordan", picture: "http://a.espncdn.com/photo/2009/1203/nba_g_jordan_sy_576.jpg", video: "https://www.youtube.com/embed/vdPQ3QxDZ1s?autoplay=1", text: "Jordan over Russell")
Memory.create(name: "Blue Jays", picture: "http://mlb.mlb.com/assets/images/4/8/0/152630480/cuts/JoeCarter_mf6x6vhg_gjr8p4k9.jpg", video: "https://www.youtube.com/embed/LIWXEYRBUgA?autoplay=1", text: "Blue Jays")
Memory.create(name: "Reggie Miller", picture: "http://static1.squarespace.com/static/557cd2bfe4b0d0b21b873542/t/55da72b1e4b001723c12a5fd/1440379571019/", video: "https://www.youtube.com/embed/MgJ_MZWg3iw?autoplay=1", text: "Reggie Miller")
Memory.create(name: "Tiger Woods", picture: "http://www.augusta.com/sites/default/files/imagecache/superphoto/1997woods1.jpg", video: "https://www.youtube.com/embed/zPWadJ5oWeU?autoplay=1", text: "Tiger Woods")
Memory.create(name: "The Dream Team", picture: "http://a.fssta.com/content/dam/fsdigital/fscom/What%20If%20Sports/2016/07/13/071316-1992-Dream-Team-Olympics-PI.jpg", video: "https://www.youtube.com/embed/Hhnj-kr9_Zs?autoplay=1", text: "The Dream Team")
Memory.create(name: "The Rock", picture: "https://cdn0.vox-cdn.com/thumbor/AEcYPMUqRMyCvXwUUo1LMRiW8Ek=/0x0:799x533/1310x873/cdn0.vox-cdn.com/uploads/chorus_image/image/46311244/The_Rock.0.jpg", video: "https://www.youtube.com/embed/HcFcDlZXH7U?autoplay=1", text: "The Rock")
Memory.create(name: "Tony Hawk", picture: "http://bluntiq.com/media/blnt/2016/06/tony-hawk-posts-character-select-teaser-for-new-ga_crnk.1920.jpg", video: "https://www.youtube.com/embed/e4QGnppJ-ys?autoplay=1", text: "Tony Hawk")
Memory.create(name: "Kobe Bryant", picture: "http://static5.businessinsider.com/image/54de1f93ecad04896f4ca01d-1190-625/where-are-they-now-the-players-from-kobe-bryants-legendary-1996-nba-draft.jpg", video: "https://www.youtube.com/embed/0v2aJdD_L3M?autoplay=1", text: "Kobe Bryant")
Memory.create(name: "Final Fantasy VII", picture: "http://therichest.imgix.net/2015/02/Final-Fantasy-VII.jpg?auto=format&q=40&lossless=1&w=1000&h=859&fit=crop", video: "https://www.youtube.com/embed/utVE4aUKYuY?autoplay=1", text: "Final Fantasy VII")
Memory.create(name: "Pokemon Yellow", picture: "https://www.loveroms.com/assets/data/gameboy-color/pokemon_yellow_cover_art_by_comunello76-d4xfrr5.jpg", video: "https://www.youtube.com/embed/GumxTf9odQ4?autoplay=1", text: "Pokemon Yellow")
Memory.create(name: "Doom", picture: "http://therichest.imgix.net/2015/02/Doom1.jpg?auto=format&q=40&lossless=1&w=1000&h=952&fit=crop", video: "https://www.youtube.com/embed/JRvSyjzUnKc?autoplay=1", text: "Doom")
Memory.create(name: "Banjo Kazooie", picture: "http://vignette4.wikia.nocookie.net/banjokazooie/images/8/85/BKXBLA.jpg/revision/latest?cb=20100425073900", video: "https://www.youtube.com/embed/3wiv-mQPl5M?autoplay=1", text: "Banjo Kazooie")
Memory.create(name: "Yoshi's Island", picture: "http://therichest.imgix.net/2015/02/Yoshis-Island.jpg?auto=format&q=40&lossless=1&w=1000&h=731&fit=crop", video: "https://www.youtube.com/embed/Qv-6NzxgObw?autoplay=1", text: "Yoshi's Island")
Memory.create(name: "Resident Evil 2", picture: "http://therichest.imgix.net/2015/02/Resident-Evil-2.jpg?auto=format&q=40&lossless=1&w=950&h=950&fit=crop", video: "https://www.youtube.com/embed/aFvyLkws6jE?autoplay=1", text: "Resident Evil 2")
Memory.create(name: "Super Metroid", picture: "http://199.101.98.242/media/images/35792-Super_Metroid_(Europe)_(En,Fr,De)-14.jpg", video: "https://www.youtube.com/embed/HUtbZYVctSw?autoplay=1", text: "Super Metroid")
Memory.create(name: "Sonic the Hedgehog", picture: "https://lh5.ggpht.com/PYenvBD0jyeXaFy7tfd1-DajFXeWLtgFj9LxLx7rlbHZAzOxokDD7JgaO-XZST1CmC4=h900", video: "https://www.youtube.com/embed/aHmrTeNfrvc?autoplay=1", text: "Sonic the hedgehog")
Memory.create(name: "The Legend of Zelda", picture: "http://therichest.imgix.net/2015/02/Links-Awakening.jpg?auto=format&q=40&lossless=1&w=1000&h=892&fit=crop", video: "https://www.youtube.com/embed/HRSmAHBeZJI?autoplay=1", text: "Legend of Zelda")
Memory.create(name: "Zombies ate my neighbors", picture: "http://theclassicgamer.com/wp-content/uploads/2014/03/2364727-snes_zombiesatemyneighbors.jpg", video: "https://www.youtube.com/embed/ut9oWWI0mWM?autoplay=1", text: "Zombies ate my neighbors")
Memory.create(name: "Smells like teen spirit", picture: "https://i.ytimg.com/vi/hTWKbfoikeg/maxresdefault.jpg", video: "https://www.youtube.com/embed/hTWKbfoikeg?autoplay=1", text: "Smells Like Teen Spirit")
Memory.create(name: "I want it that way", picture: "https://i.ytimg.com/vi/4fndeDfaWCg/maxresdefault.jpg", video: "https://www.youtube.com/embed/4fndeDfaWCg?autoplay=1", text: "Backstreet Boys")
Memory.create(name: "I Will Always Love You", picture: "http://cps-static.rovicorp.com/3/JPG_500/MI0002/005/MI0002005583.jpg?partner=allrovi.com", video: "https://www.youtube.com/embed/3JWTaaS7LdU?autoplay=1", text: "Whitney Houston")
Memory.create(name: "U Can't Touch This", picture: "https://images-na.ssl-images-amazon.com/images/I/51A1S1Dy6GL.jpg", video: "https://www.youtube.com/embed/otCpCn0l4Wo?autoplay=1", text: "MC Hammer")
Memory.create(name: "My Heart Will Go On", picture: "http://www.recapo.com/wp-content/uploads/2014/05/dion-heart-.png", video: "https://www.youtube.com/embed/7KBQLgeKRbg?autoplay=1", text: "Celine Dion")
Memory.create(name: "My Name Is", picture: "https://i.ytimg.com/vi/mxZNDis3PH8/maxresdefault.jpg", video: "https://www.youtube.com/embed/sNPnbI1arSE?autoplay=1", text: "Eminem")
Memory.create(name: "Livin La Vida Loca", picture: "https://i.ytimg.com/vi/sqFhxkzc6s8/hqdefault.jpg", video: "https://www.youtube.com/embed/p47fEXGabaY?autoplay=1", text: "Ricky Martin")
Memory.create(name: "Ice Ice Baby", picture: "http://images.mastermp3.net/artwork/nw/nwd7fb6f213cd5046bc203c55eba0b18ed.jpg", video: "https://www.youtube.com/embed/rog8ou-ZepE?autoplay=1", text: "Vanilla Ice")
Memory.create(name: "Tearin' Up My Heart", picture: "http://cdn.playbuzz.com/cdn/27235930-2ad1-4bed-897c-1dac87708c5c/0eb7dd96-6c89-4324-be21-a0831f47e1d8.jpg", video: "https://www.youtube.com/embed/LRKiftk6ffQ?autoplay=1", text: "NSYNC")
Memory.create(name: "California Love", picture: "https://i.ytimg.com/vi/5wBTdfAkqGU/maxresdefault.jpg", video: "https://www.youtube.com/embed/5wBTdfAkqGU?autoplay=1", text: "2pac")
Memory.create(name: "Friends", picture: "http://img2.tvtome.com/i/u/0aa3afb3cbe3468fc6e43e50070b0810.png", video: "https://www.youtube.com/embed/Xs-HbHCcK58?autoplay=1", text: "Friends")
Memory.create(name: "X-Files", picture: "http://www.telegraph.co.uk/content/dam/tv/2016/01/28/X_Files_main-large_trans++pJliwavx4coWFCaEkEsb3kvxIt-lGGWCWqwLa_RXJU8.jpg", video: "https://www.youtube.com/embed/uBoMEKL7HFc?autoplay=1", text: "X-Files")
Memory.create(name: "Fresh-Prince of Bel Air", picture: "https://i.ytimg.com/vi/AVbQo3IOC_A/hqdefault.jpg", video: "https://www.youtube.com/embed/hBe0VCso0qs?autoplay=1", text: "Fresh-Prince")
Memory.create(name: "The Simpsons", picture: "http://i.kinja-img.com/gawker-media/image/upload/tv1gpytvw4wuhyx6ykcw.jpg", video: "https://www.youtube.com/embed/SR8WWFzrZAg?autoplay=1", text: "The Simpsons")
Memory.create(name: "Buffy the Vampire Slayer", picture: "http://www.thefactsite.com/wp-content/uploads/2015/05/buffy-vampire-slayer.jpg", video: "https://www.youtube.com/embed/o8IcBhQkBjw?autoplay=1", text: "Buffy the Vampire Slayer")
Memory.create(name: "Full House", picture: "http://a.abcnews.com/images/Entertainment/GTY_FULL_HOUSE_150421_DG_4x3_992.jpg", video: "https://www.youtube.com/embed/2EL65KLdEHE?autoplay=1", text: "Full House")
Memory.create(name: "Titanic", picture: "https://i.ytimg.com/vi/Jrv95rcDR5Q/maxresdefault.jpg", video: "https://www.youtube.com/embed/nYu5I8_-1-Y?autoplay=1", text: "Titanic")
Memory.create(name: "The Sixth Sense", picture: "http://2.bp.blogspot.com/-awM0tkhlJCM/VfCCApDZGPI/AAAAAAAABW0/BkiXvcP8bhs/s1600/THE%2BSIXTH%2BSENSE.png", video: "https://www.youtube.com/embed/VG9AGf66tXM?autoplay=1", text: "The Sixth Sense")
Memory.create(name: "Forest Gump", picture: "http://cdn.playbuzz.com/cdn/e5168485-dfc3-45f6-89ad-47761d121ad6/a3215225-7f2b-4afd-803c-0a3b3276f9a2.jpg", video: "https://www.youtube.com/embed/bLvqoHBptjg?autoplay=1", text: "Forest Gump")
Memory.create(name: "Terminator 2", picture: "https://d2ycltig8jwwee.cloudfront.net/features/671/fullwidth.728bfded.jpg", video: "https://www.youtube.com/embed/lwSysg9o7wE?autoplay=1", text: "Terminator 2")
Memory.create(name: "Braveheart", picture: "http://images6.fanpop.com/image/photos/32100000/Wallpaper-braveheart-32189752-1920-1080.jpg", video: "https://www.youtube.com/embed/wj0I8xVTV18?autoplay=1", text: "Braveheart")
Memory.create(name: "Fightclub", picture: "http://s3.foxmovies.com/foxmovies/production/films/93/images/feature/film-page-feature-image-front-main-stage-1.jpg", video: "https://www.youtube.com/embed/SUXWAEX2jlg?autoplay=1", text: "Fight Club")
Memory.create(name: "Jurassic Park", picture: "https://cdn0.vox-cdn.com/thumbor/w2xGdkawdst33t7qmat3iqvJj3o=/0x0:1024x683/1280x854/cdn0.vox-cdn.com/assets/1010916/jurassic-park.png", video: "https://www.youtube.com/embed/lc0UehYemQA?autoplay=1", text: "Jurassic Park")
Memory.create(name: "Good Will Hunting", picture: "http://images.mentalfloss.com/sites/default/files/styles/article_640x430/public/good_will_large.jpg", video: "https://www.youtube.com/embed/PaZVjZEFkRs?autoplay=1", text: "Good Will Hunting")
Memory.create(name: "Toy Story", picture: "http://www.gstatic.com/tv/thumb/movieposters/17420/p17420_p_v8_ab.jpg", video: "https://www.youtube.com/embed/KYz2wyBy3kc?autoplay=1", text: "Toy Story")

Memory.create(name: "Recess", picture: "http://vignette1.wikia.nocookie.net/recess/images/7/7f/Recess.jpg/revision/latest?cb=20130711002842", video: "https://www.youtube.com/embed/jvRlyA3uUW0?autoplay=1", text: "Recess")
Memory.create(name: "Dragon Ball Z", picture: "https://i.ytimg.com/vi/LqSg9yVfzV0/maxresdefault.jpg", video: "https://www.youtube.com/embed/1GYYV5a5B_o?autoplay=1", text: "Dragon Ball Z")
Memory.create(name: "Teen Titans", picture: "http://vignette3.wikia.nocookie.net/teentitans/images/8/8c/Teen_titans.png/revision/latest?cb=20150212183135", video: "https://www.youtube.com/embed/QWaWvQuIVMI?autoplay=1", text: "Teen Titans")
Memory.create(name: "Jackie Chan Adventures", picture: "http://www.writtenbyjoelle.com/stills/logo/logo-tv-jackie-chan-adventures_full.jpg", video: "https://www.youtube.com/embed/ZLdDjLEIpzI?autoplay=1", text: "Jackie Chan Adventures")
Memory.create(name: "Jackie Chan Adventures", picture: "http://www.writtenbyjoelle.com/stills/logo/logo-tv-jackie-chan-adventures_full.jpg", video: "https://www.youtube.com/embed/ZLdDjLEIpzI?autoplay=1", text: "Jackie Chan Adventures")
Memory.create(name: "Static", picture: "http://www.writtenbyjoelle.com/stills/logo/logo-tv-jackie-chan-adventures_full.jpg", video: "https://www.youtube.com/embed/2KWeKZyxEZA?autoplay=1", text: "Static Shock")
Memory.create(name: "Digimon", picture: "http://i1.kym-cdn.com/entries/icons/original/000/016/413/Digimon-Frontier-Episode-50-English-Dubbed.jpg", video: "https://www.youtube.com/embed/cn9ACo4ScUU?autoplay=1", text: "Digimon")
Memory.create(name: "Avatar", picture: "http://img.wallpaperfolder.com/f/42B4D7EF0B6C/avatar-last-airbender-aang-air.jpg", video: "https://www.youtube.com/embed/szKZ0keja-g?autoplay=1", text: "Avatar")
Memory.create(name: "Xiaolin Showdown", picture: "http://vignette1.wikia.nocookie.net/xiaolinpedia/images/6/6a/Xiaolin_Showdown.jpg/revision/latest?cb=20130219011632", video: "https://www.youtube.com/embed/HnMnOSU2S5Q?autoplay=1", text: "Xiaolin Showdown")
Memory.create(name: "X-men evolution", picture: "http://statici.behindthevoiceactors.com/behindthevoiceactors/_img/shows/banner_3.jpg", video: "https://www.youtube.com/embed/6faj24XtmP8?autoplay=1", text: "X-men Evolution")

Memory.create(name: "2008 Boston Celtics", picture: "http://orig03.deviantart.net/9eb4/f/2012/362/f/5/boston_celtics_2008_champions_by_31andonly-d5pj4px.jpg", video: "https://www.youtube.com/embed/BAyA8BV-cTI?autoplay=1", text: "2008 Boston Celtics")
Memory.create(name: "Mario Chalmer's shot", picture: "https://i.ytimg.com/vi/o5BhakOnwvc/maxresdefault.jpg", video: "https://www.youtube.com/embed/pDvbTrE8VBo?autoplay=1", text: "2008 NCAA Championship")
Memory.create(name: "2007 Fiesta Bowl", picture: "https://static01.nyt.com/images/2007/01/02/sports/fiesta.1.600.jpg", video: "https://www.youtube.com/embed/-5wjbc-UbHQ?autoplay=1", text: "2007 Fiesta Bowl")
Memory.create(name: "2006 Rose Bowl", picture: "http://3.bp.blogspot.com/-oGK3_Ampbao/UOYLoSmcAoI/AAAAAAAABa0/INxa1rfMTxc/s640/05football.583.jpg", video: "https://www.youtube.com/embed/s8zZRBTOcnY?autoplay=1", text: "2006 Rose Bowl")
Memory.create(name: "Kobe Bryant 81", picture: "http://www.wdkx.com/wdkxwp/wp/wp-content/uploads/2016/01/kobe81-252x300.jpg", video: "https://www.youtube.com/embed/wV9CMVdY3dM?autoplay=1", text: "Kobe Bryant 81")
Memory.create(name: "Aaron Boone Walkoff", picture: "https://cdn0.vox-cdn.com/thumbor/5V2aYIG8GKBZ7lRsCSmzkp78FTE=/cdn0.vox-cdn.com/uploads/chorus_asset/file/2364284/97278822.0.jpg", video: "https://www.youtube.com/embed/CLY16wmHdUk?autoplay=1", text: "Aaron Boone Walk-Off")
Memory.create(name: "2004 World Series", picture: "http://yawkeywayreport.com/wp-content/uploads/2013/11/sox-2004-ws-celebration1.jpg", video: "https://www.youtube.com/embed/KCBFjmtLgSI?autoplay=1", text: "2004 World Series")
Memory.create(name: "Lezak saves the day", picture: "http://cdn-s3.si.com/s3fs-public/si/dam/assets/13/01/16/130116192201-jason-lezak-single-image-cut.jpg", video: "https://www.youtube.com/embed/sxy920Nd7yY?autoplay=1", text: "2008 Olympics")
Memory.create(name: "Usain Bolt", picture: "http://i.dailymail.co.uk/i/pix/2016/05/18/23/13FEA647000005DC-3597636-image-a-10_1463610454800.jpg", video: "https://www.youtube.com/embed/qslbf8L9nl0?autoplay=1", text: "2008 Olympics")
Memory.create(name: "Tracy McGrady 13 points", picture: "http://fadeawayworld.com/wp-content/uploads/2016/07/Screen-shot-2015-03-04-at-6.08.42-PM.png", video: "https://www.youtube.com/embed/M-8FksMVAdU?autoplay=1", text: "Tracy McGrady")

Memory.create(name: "Halo", picture: "https://content.halocdn.com/media/Default/games/halo-3/media/h3_010-68adc78167c54528b438982a40ff04a7.jpg", video: "https://www.youtube.com/embed/9z36WDj2PcU?autoplay=1", text: "Halo")
Memory.create(name: "God of War", picture: "https://i.kinja-img.com/gawker-media/image/upload/mvttykblep1yahxzocsd.jpg", video: "https://www.youtube.com/embed/jZkX3LJDeYQ?autoplay=1", text: "God of War")
Memory.create(name: "Rock Band", picture: "https://upload.wikimedia.org/wikipedia/en/e/e6/Rock_band_2_screen.jpg", video: "https://www.youtube.com/embed/IiXMHLTZxkY?autoplay=1", text: "Rockband")
Memory.create(name: "Guitar Hero 3", picture: "http://cheats.today/wp-content/uploads/2015/02/guitarhero3.jpg", video: "https://www.youtube.com/embed/PRDj1_5ekxg?autoplay=1", text: "Guitar Hero 3")
Memory.create(name: "Super Smash Bros", picture: "http://vignette1.wikia.nocookie.net/metroid/images/c/cb/SuperSmashBrosWallpaper1024.jpg/revision/latest?cb=20100129184908", video: "https://www.youtube.com/embed/O0O173xIuO0?autoplay=1", text: "Super Smash Bros")
Memory.create(name: "Gears of War", picture: "http://mock9.com/wp-content/uploads/2016/04/gears-movie.jpg", video: "https://www.youtube.com/embed/ccWrbGEFgI8?autoplay=1", text: "Gears of War")
Memory.create(name: "Grand Theft Auto Vice City", picture: "http://oyster.ignimgs.com/mediawiki/apis.ign.com/grand-theft-auto-vice-city/thumb/9/9c/Grand_theft_auto_vice_city_by_progressivez-d38prca.jpg/460px-Grand_theft_auto_vice_city_by_progressivez-d38prca.jpg", video: "https://www.youtube.com/embed/MpmDawqOfqs?autoplay=1", text: "GTA")
Memory.create(name: "Call of Duty Modern Warfare", picture: "http://cdn.akamai.steamstatic.com/steam/apps/7940/header.jpg?t=1450407162", video: "https://www.youtube.com/embed/ETFFyw2Btoc?autoplay=1", text: "Call of Duty Modern Warfare")
Memory.create(name: "Bioshock", picture: "http://cdn.akamai.steamstatic.com/steam/apps/7670/header.jpg?t=1473385497", video: "https://www.youtube.com/embed/CoYorK3E4aM?autoplay=1", text: "Bioshock")
Memory.create(name: "Diablo 2", picture: "https://i.ytimg.com/vi/VP9NZPAX_dA/maxresdefault.jpg", video: "https://www.youtube.com/embed/811BbJhnUjM?autoplay=1", text: "Diablo 2")

Memory.create(name: "Lose Yourself", picture: "https://i.ytimg.com/vi/kaAvmGe8MVk/maxresdefault.jpg", video: "https://www.youtube.com/embed/_Yhyp-_hX2s?autoplay=1", text: "Lose Yourself")
Memory.create(name: "Umbrella", picture: "https://i.ytimg.com/vi/REd_dPxKMxU/hqdefault.jpg", video: "https://www.youtube.com/embed/CvBfHwUxHIk?autoplay=1", text: "Umbrella")
Memory.create(name: "Poker Face", picture: "http://img13.deviantart.net/fb81/i/2016/047/b/e/poker_face___lady_gaga_by_ale93lol-d7qob5v.jpg", video: "https://www.youtube.com/embed/bESGLojNYSo?autoplay=1", text: "Poker Face")
Memory.create(name: "I Kissed a Girl", picture: "http://2.bp.blogspot.com/-qXnUbfqnP2Y/VMr6K2PwCBI/AAAAAAAAImg/3ltXrwUQV9s/s1600/I-Kissed-A-Girl-katy-perry-should-we-like-it.jpg", video: "https://www.youtube.com/embed/tAp9BKosZXs?autoplay=1", text: "I Kissed a girl")
Memory.create(name: "Get Low", picture: "http://ec1.images-amazon.com/images/I/618PRPZQ1BL._SS500_.jpg", video: "https://www.youtube.com/embed/IYH7_GzP4Tg?autoplay=1", text: "Get Low")
Memory.create(name: "Empire State of Mind", picture: "http://images.8tracks.com/cover/i/008/761/523/IMG_4889-2310.jpg?rect=0,0,1280,1280&q=98&fm=jpg&fit=max&w=640&h=640", video: "https://www.youtube.com/embed/qTESW95Ly5E?autoplay=1", text: "Empire State of Mind")
Memory.create(name: "Apologize", picture: "http://az616578.vo.msecnd.net/files/2015/11/23/635838380217943606-151680032_apologize-bootleg-cover.jpg", video: "https://www.youtube.com/embed/ZSM3w1v-A_Y?autoplay=1", text: "Apologize")
Memory.create(name: "How to save a life", picture: "http://direct-ns.rhap.com/imageserver/v2/albums/Alb.7568270/images/500x500.jpg", video: "https://www.youtube.com/embed/cjVQ36NhbMk?autoplay=1", text: "How to save a life")
Memory.create(name: "Breaking the Habit", picture: "http://i.ytimg.com/vi/v2H4l9RpkwM/0.jpg", video: "https://www.youtube.com/embed/v2H4l9RpkwM?autoplay=1", text: "Breaking the Habit")
Memory.create(name: "Viva la Vida", picture: "http://www.coldplay.com/recordings/art_vivalavida.jpg", video: "https://www.youtube.com/embed/dvgZkm1xWPE?autoplay=1", text: "Viva la Vida")


















